---
sidebar: sidebar 
permalink: concept_overview_API_service.html 
keywords: API services, access token, refresh token, API Catalog 
summary: API 서비스 기능에 대한 개요를 제공합니다. 
---
= API 서비스 이해
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Active IQ API Services는 자동화를 사용하여 워크플로우에 효율성을 추가합니다. API 서비스 내부에는 20개 이상의 서비스 영역으로 그룹화된 100개 이상의 서로 다른 API 엔드포인트를 설명하는 * API Catalog * 가 있습니다. NetApp 고객은 이러한 API를 사용하여 시스템 정보, 스토리지 효율성, 성능, 상태 및 업그레이드와 같은 다양한 관심 영역을 이용할 수 있습니다.

API는 Active IQ Digital Advisor에 프로그래밍 방식으로 연락하여 데이터를 컴퓨팅 환경으로 다시 가져올 수 있는 간단한 코드를 작성할 수 있는 인터페이스입니다. Active IQ 디지털 어드바이저에게 매일 연락하여 관심 있는 영역의 최신 데이터를 다시 가져오는 방식으로 코드를 작성할 수 있습니다. 그런 다음 이 데이터를 사용하여 발권 시스템을 채우거나 자신만의 대시보드, 웹 페이지 또는 보고서를 만들 수 있습니다. Active IQ API 카탈로그에는 코드 샘플과 브라우저에서 API를 사용해 볼 수 있는 기능이 모두 포함되어 있습니다.

API를 통한 자동화는 일상적인 또는 주간 작업에 효율성과 정확성을 더할 수 있는 좋은 방법입니다. 리소스를 확보하여 더욱 복잡한 작업을 수행하거나 새 워크플로우를 자동화할 수 있습니다. 예를 들어, 수정해야 할 시스템 상태 위험이 있는 경우 Active IQ 디지털 어드바이저의 이러한 항목 풀아웃 및 티켓 시스템에 대한 푸시를 자동화할 수 있습니다.



== API 카탈로그

페이지 상단의 토글을 사용하면 두 가지 모드 사이를 전환하여 카탈로그를 볼 수 있습니다. 코드 보기에서는 필요한 입력 매개 변수, 반환 데이터의 내용 및 형식, 사용자가 코드를 직접 입력할 수 있도록 코드 샘플에 초점을 맞춥니다. 실험 보기는 사용자에게 기본 API 서비스 페이지에서 가져온 토큰을 사용하여 브라우저에서 API를 "사용해" 볼 수 있는 기회를 제공합니다.

두 보기 중 하나를 사용하면 왼쪽의 탐색 창을 사용하여 사용 가능한 항목을 탐색할 수 있습니다. 항목은 서비스별로 사전순으로 구성되어 있습니다. 지정된 서비스 내에서 제목을 확장하여 개별 API 끝점을 표시할 수 있습니다. 서비스 제목 또는 API 끝점을 클릭하면 가운데 창에 있는 카탈로그의 해당 섹션으로 이동합니다.



== API 사용

일단 권한이 부여되고 토큰을 생성할 수 있으면 토큰을 활용하여 프로그래밍 방식의 쿼리를 만들고 데이터를 검색할 수 있습니다. API 카탈로그에서 API를 테스트하여 쿼리의 작동 방식과 반환되는 데이터의 유형을 직접 확인할 수도 있습니다. 이 방법은 시스템에서 코드 프레임워크를 구축하기 전에 API가 어떻게 작동하는지 이해하는 데 유용합니다.

video::GQskCeCrtQA[youtube,width=848,height=480]