---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: digital advisor, features, upgrade, support offering 
summary: 대시보드, 시청목록, 기능 및 위젯에 대한 정보를 제공합니다. 
---
= Digital Advisor 기능 이해
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Digital Advisor를 사용하여 관심 목록 레벨에서 스토리지 시스템의 전체 상태, 시스템 상태, 재고, 계획, 업그레이드 및 중요한 통찰력을 확인할 수 있습니다.

처음 디지털 어드바이저에 액세스할 때 감시 목록을 생성하거나 고객 이름, 사이트 이름, 그룹 이름, StorageGRID, 호스트 이름을 검색할 수 있습니다. 클러스터, 일련 번호 또는 시스템 ID

또한 위험 심각도와 유형을 나타내는 카드에 적용된 색상도 알고 있어야 합니다.

다음은 Digital Advisor의 몇 가지 기능입니다.

* 여러 감시 목록, 실행 가능한 유용한 정보 보기를 한 눈에 볼 수 있습니다.
* 스토리지 시스템의 모든 위험과 위험 완화를 위한 조치에 대한 통찰력을 확보할 수 있습니다.
* Active IQ Unified Manager를 사용하여 위험 완화
* 스토리지 시스템을 업그레이드합니다.
* 지속 가능성 점수와 예상 전력, 직접 탄소, 열 사용량을 확인하십시오. 지속 가능성 점수를 기준으로 스토리지 시스템의 전반적인 효율성을 평가하고 NetApp의 권장 조치에 따라 점수를 높이십시오. link:concept_understand_sustainability_dashboard.html["자세한 정보"].
* ONTAP 9.1 이상을 실행하는 스토리지 시스템의 데이터 축소율, 사용된 논리적 공간, 사용된 물리적 공간 및 저장된 총 데이터를 확인하십시오.
* 성능 데이터의 그래픽 형식을 확인하여 스토리지 디바이스의 성능을 분석할 수 있습니다.
* 향후 6개월 이내에 만료되었거나 거의 만료된 하드웨어 및 소프트웨어에 대한 정보를 확인하십시오.
* Ansible을 사용하여 ONTAP 펌웨어를 업데이트하십시오.
* 90% 용량을 초과하거나 90% 용량에 근접하는 시스템에 대한 세부 정보를 확인하십시오.
* 클러스터 및 노드 구성 요약, 로컬 계층 및 볼륨 정보, 네트워크 인터페이스 및 포트 정보, 디스크 및 셸프에 대한 정보를 자세히 설명하는 스택 다이어그램, 케이블 시각화를 비롯한 자세한 물리적 및 논리적 구성 정보를 봅니다.
* 문제 해결, 업그레이드 평가, 솔루션 검증 및 마이그레이션에 도움이 되는 교차 스택 정보와 통찰력을 제공합니다.
* 호스트의 호환성을 확인하고 호스트 운영 체제, 드라이버 및 에 대한 업그레이드 권장 사항을 제공합니다.
* 원하는 것을 더 스마트하고 빠르게 찾을 수 있습니다.



NOTE: 시스템 대시보드의 * Configuration * 위젯에서 지원 오퍼링을 업그레이드하여 설치 기반에 대한 통찰력을 얻고 맞춤형 지원을 받을 수 있습니다.
