---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'Digital Advisor가 이제 BlueXP와 완전히 통합되었습니다. 이제 클러스터를 관리하고 BlueXP UI(사용자 인터페이스)에서 Digital Advisor의 모든 기능에 액세스할 수 있습니다.' 
---
= BlueXP와 디지털 어드바이저 통합
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisor가 이제 BlueXP와 완전히 통합되었습니다. 이제 클러스터를 관리하고 BlueXP UI(사용자 인터페이스)에서 Digital Advisor의 모든 기능에 액세스할 수 있습니다.

IT 전문가와 클라우드 설계자는 BlueXP를 사용하여 하이브리드 멀티 클라우드 인프라를 중앙에서 관리할 수 있습니다. BlueXP의 디지털 어드바이저에 액세스하려면 NetApp Support 사이트(NSS) 계정만 있으면 됩니다.



== 통합 개요

2022년 11월부터 Digital Advisor 사용자는 BlueXP에서 Digital Advisor를 사용하는 것이 좋습니다. BlueXP에서 사용하던 것과 동일한 Digital Advisor 인터페이스에 액세스할 수 있습니다. BlueXP를 사용하면 클라우드 스토리지(예: Cloud Volumes ONTAP)를 생성 및 관리하고, NetApp의 데이터 서비스(예: 클라우드 백업)를 사용하고, 많은 사내 및 에지 스토리지 장치를 제어할 수 있습니다.



== BlueXP의 Digital Advisor에 액세스합니다

BlueXP의 Digital Advisor에 액세스하여 클러스터를 관리할 수 있습니다.

.단계
. 웹 브라우저를 열고 로 이동합니다 https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^].
. NetApp Support 사이트 자격 증명으로 로그인 * 을 선택하고 자격 증명을 입력합니다.
+
이전에 전자 메일 및 암호를 사용하여 BlueXP 로그인을 만든 경우 대신 해당 로그인 옵션을 계속 사용해야 합니다.

. 메시지가 표시되면 NetApp Support 사이트 자격 증명을 사용하여 로그인합니다.
+
이 로그인은 2단계에서 완료한 로그인과 다릅니다. 2단계에서 BlueXP 플랫폼에 로그인했습니다. 이제 Digital Advisor에 로그인했습니다.



결과 *

기존의 모든 관심 목록과 구성이 표시되며, 이제 Digital Advisor를 일반적인 방식으로 사용할 수 있습니다.



== BlueXP에 대해 자세히 알아보십시오

https://docs.netapp.com/us-en/bluexp-family/index.html["자세한 내용은 BlueXP 설명서를 참조하십시오"^]
