---
sidebar: sidebar 
permalink: learn_BlueXP_sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP 
summary: 에너지 소비를 줄이고 환경 목표를 달성할 수 있는 지속 가능성에 대한 정보를 제공합니다. 
---
= 지속 가능성에 대해 자세히 알아보십시오
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
지속 가능성은 서비스로서 에너지 소비를 줄이고 환경 목표를 향해 작업할 수 있도록 합니다. 이를 통해 스토리지 시스템을 환경 친화적 방식에 맞춰 지속 가능성 목표를 달성할 수 있습니다.

Sustainability 대시보드에서 지속 가능성 점수와 예상 전력 사용량, 직접 탄소 및 열 사용량을 볼 수 있습니다. 특정 사이트에 대한 탄소 완화 비율을 조정할 수 있습니다. 또한 클러스터 수준에서 지속 가능성 점수를 볼 수도 있습니다. 지속 가능성 점수를 기준으로 지속 가능성 자세를 평가하고 NetApp이 권장하는 조치를 시행하여 점수를 향상할 수 있습니다. Sustainability 대시보드에 대한 자세한 내용은 을 참조하십시오 link:BlueXP_sustainability_dashboard_overview.html["Sustainability 대시보드 개요"].


NOTE: 지속 가능성은 Cloud Volumes ONTAP, AFF 시스템(A-Series 및 C-Series), E-Series, FAS, StorageGRID 시스템에서 지원됩니다.

Sustainability 대시보드를 이해하기 위해 다음 비디오를 볼 수 있습니다.

video::yNRHeOvbGX8[youtube,width=848,height=480]


== 지속 가능성의 이점

지속 가능성은 다음과 같은 이점을 제공합니다.

* 동일한 양의 데이터를 저장할 스토리지 장치의 수를 줄여 성능을 향상합니다.
* 스토리지 시스템 활용률을 최적화하여 스토리지 비용 절감
* 데이터 센터에서 재생 가능 에너지를 사용하여 탄소 발자국을 줄입니다.
* 에너지 효율적인 정책을 구현하여 에너지 효율성을 개선합니다.

