---
sidebar: sidebar 
permalink: reference_limitations_activeiq.html 
keywords: limitation, issues, not supported, drawbacks 
summary: 릴리스의 제한 사항에 대한 자세한 내용은 에 나와 있습니다. 
---
= 알려진 제한 사항
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.

다음과 같은 제한 사항이 있습니다.

* 7-Mode로 운영되는 Data ONTAP 스토리지 시스템의 경우(7-Mode로 운영되는 Data ONTAP 스토리지 시스템의 지원 종료 시기가 임박)
+
** 성능 차트
** 스토리지 효율성


* Upgrade Advisor는 9.0 이전의 clustered ONTAP에 대한 업그레이드 계획을 지원하지 않습니다.




== 감시 목록을 편집하는 데는 60분 정도 걸릴 수 있습니다

감시 목록을 편집해도 Digital Advisor의 정보는 즉시 업데이트되지 않습니다. 디지털 어드바이저에게 변경 사항이 반영되려면 최대 60분이 걸릴 수 있습니다.



== 보고서를 예약하는 동안 빈 보고서가 표시됩니다

예약된 보고서는 SupportEdge Advisor 또는 SupportEdge Expert 지원 계약에서만 사용할 수 있습니다. 시스템에 SupportEdge Advisor 또는 SupportEdge Expert 지원 계약이 없을 경우 보고서를 예약하는 동안 빈 보고서가 나타날 수 있습니다.



== 승인되고 확인되지 않은 위험은 디지털 어드바이저에 반영되기까지 60분이 걸릴 수 있습니다

승인되고 확인되지 않은 위험의 상태는 Digital Advisor에 즉시 반영되지 않습니다. 변경 사항이 Digital Advisor 및 Wellness Report에 반영되려면 최대 60분이 소요될 수 있습니다.



== 클러스터 및 일련 번호에 AutoSupport 위젯을 사용할 수 없습니다

AutoSupport 위젯은 클러스터 및 일련 번호 검색에 대한 경고를 제공하지 않습니다.



== AutoSupport 위젯이 직렬 레벨 AutoSupport 세부 정보로 드릴다운할 수 없습니다

AutoSupport 보고 페이지에서 상태, 최근에 전송을 중지한 시스템 또는 AutoSupport가 꺼진 시스템을 클릭해도 상태 점검 화면으로 이동하지 않습니다.



== 재고 위젯에서는 필터링 및 정렬을 사용할 수 없습니다

재고 위젯에서는 데이터를 필터링하고 정렬할 수 없습니다. "필터 기준" 드롭다운에서 ONTAP AFF, ONTAP ASA, ONTAP Edge 또는 ONTAP Select를 선택하면 데이터가 표시되지 않습니다.
