---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: 스토리지 시스템의 용량 세부 정보 및 스토리지 효율성 절감 효과를 확인합니다. 
---
= Digital Advisor 에서 용량 및 스토리지 효율성 절감 효과를 확인하세요.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
시스템의 용량 세부 정보 및 스토리지 효율성 절감 효과를 확인하고 적절한 조치를 취할 수 있습니다. 용량 및 스토리지 효율성 정보는 클러스터 레벨 또는 노드 레벨에서 확인할 수 있습니다.


NOTE: 이 기능은 E-Series 시스템에서 지원되지 않습니다.

용량 대시보드는 시스템의 용량 세부 정보와 용량 예측을 표시합니다. 용량 예측은 기간별 용량 정보를 활용하여 각 시스템의 사용률을 파악합니다. 사용 및 할당된 용량의 기간별 데이터(가능한 경우 1년치 데이터)를 기반으로, 알고리즘은 각 시스템의 현재 사용률을 고려하여 향후 1개월에서 6개월 동안의 시스템 사용률을 예측합니다.

스토리지 효율성 대시보드는 데이터 감소율, 사용된 논리 공간, 사용된 물리 공간 및 총 절약 데이터를 표시합니다. 데이터 감소율과 절약량은 AFF 시스템, 비AFF 시스템 또는 둘 다에 대해 스냅샷 복사본 사용 여부에 따라 확인할 수 있습니다. 볼륨 중복 제거, 볼륨 압축, 압축 해제, FlexClone 볼륨 및 스냅샷 복사본 등 효율성 기능별로 고객 스토리지 전체의 총 데이터 절약량을 확인할 수 있습니다. 효율성 비율이 가장 높은 상위 5개 스토리지 시스템을 볼 수 있습니다. 또한 AFF A-Series, AFF C190, All SAN Array 및 FAS500을 포함한 ONTAP 시스템의 경우 스냅샷 복사본을 제외한 SAN 및 NAS 효율성을 노드 수준에서 확인할 수 있습니다.

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.단계
. 왼쪽 창에서 *용량 및 효율성*을 선택하십시오.
+
기본적으로 * Capacity * 탭이 선택됩니다.

. 클러스터 및 노드 레벨에서 용량 세부 정보를 확인합니다.
+
.. 노드 레벨에서 용량 예측을 확인합니다.
+
ONTAP 시스템의 경우, 물리적 용량에 대한 정보는 ClusterViewer에서 확인할 수 있습니다.



. NetApp 또는 파트너에게 용량 추가를 요청하는 알림을 보내려면 *용량 추가*를 선택하십시오.
. 스토리지 효율성 및 스토리지 시스템의 데이터 절감 효과를 확인하십시오.
+
.. 스토리지 시스템의 스토리지 효율성 비율이 평균 스토리지 효율성 비율보다 높다면, *성공 사례 공유*를 선택하여 따르고 있는 모범 사례를 알려주십시오.
.. 사용 중인 스토리지 시스템의 스토리지 효율 비율이 평균 스토리지 효율 비율보다 낮다면, *문의하기*를 선택하여 스토리지 시스템의 구성을 알려 주십시오.




용량 및 스토리지 효율성에 대한 자세한 내용은 를 참조하십시오 link:reference_aiq_faq.html["Digital Advisor에 대한 FAQ(자주 묻는 질문"].
