---
sidebar: sidebar 
permalink: task-informed-decisions-based-on-cloud-recommendations.html 
keywords: cloud recommendations, migration, backup and archive, disaster recovery 
summary: 정보에 기반한 결정을 내릴 수 있는 권장 사항을 제공합니다. 
---
= 클라우드 권장사항을 기반으로 정보에 입각한 의사 결정을 내릴 수 있습니다
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Active IQ은 시스템을 지속적으로 분석하고 시스템의 성능, 효율성 및 상태를 개선하기 위한 권장 사항을 제공합니다.

Active IQ는 다음과 같은 권장 사항을 제공합니다.

* 마이그레이션: 스토리지 시스템 내에서 사용 가능한 여러 유형의 워크로드에 대한 정보를 제공하고 클라우드에서 바로 사용할 수 있는 워크로드를 식별합니다. 워크로드를 클라우드로 이동할 경우 비용을 절감하고 클라우드 재해 복구를 제공할 수 있습니다.
* Backup & Archive(백업 및 아카이브): 클라우드에 백업해야 하는 시스템에 대한 정보를 제공합니다. NetApp Cloud Backup을 사용하여 시스템을 보호하고 필요할 때 복원할 수 있습니다.
* 재해 복구: 재해 발생 시 도움이 되도록 클라우드에 복제해야 하는 데이터에 대한 정보를 제공합니다.



NOTE: Active IQ에서는 클라우드 관리자로 이동하여 권장사항을 구현합니다.

.단계
. 왼쪽 창에서 * 클라우드 권장 사항 * 을 클릭합니다.
. 데이터를 마이그레이션하려면
+
.. Migration * 창에서 링크를 클릭합니다.
.. Cloud Manager * 를 시작하려면 * 클라우드로 마이그레이션 * 을 클릭합니다.


. 데이터 백업 및 보관:
+
.. Backup & Archive * 창에서 링크를 하나 클릭합니다.
.. Cloud Manager * 를 시작하려면 * Backup to Cloud * 를 클릭합니다.


. 데이터를 복제하려면
+
.. Disaster Recovery* 창에서 하나의 링크를 클릭합니다.
.. 클라우드에 복제 * 를 클릭하여 * Cloud Manager * 를 실행합니다.



