---
sidebar: sidebar 
permalink: task_view_keystone_capacity_utilization.html 
keywords: keystone, capacity utilization, service tiers, Keystone subscription, keystone subscription, shares, disks 
summary: NetApp Keystone 유연한 서브스크립션의 용량 활용도에 대한 정보를 제공합니다. 
---
= NetApp Keystone 서브스크립션을 통해 용량 활용도를 확인할 수 있습니다
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Keystone 가입 서비스에 가입되어 있는 경우 Active IQ 디지털 자문 대시보드에서 Keystone 가입 위젯을 확인할 수 있습니다.

Keystone 가입 위젯은 계정의 용량 사용량을 요약해서 제공합니다. 이 차트는 물리적 용량에 대한 용량 활용도 차트로 구성되며 스냅샷은 마지막 5분으로 반올림됩니다. 약정 용량 이상의 사용률(버스트 용량)은 빨간색으로 표시됩니다.

위젯의 데이터를 분석하고 서비스된 모든 스토리지의 용량 및 사용 추세를 그래픽으로 나타내는 * Keystone - 용량 활용률 * 대시보드를 볼 수 있습니다 link:https://docs.netapp.com/us-en/keystone/nkfsosm_performance.html["서비스 계층"]프리미엄, 익스트림 및 표준과 같은 NetApp Keystone 가입 계정에 연결됩니다.

를 볼 수 있습니다 link:https://docs.netapp.com/us-en/keystone/nkfsosm_keystone_service_capacity_definitions.html["Keystone 구독 서비스 용량"] 및 대시보드에서 블록, 파일 서비스 또는 오브젝트 스토리지에 대해 요청된 각 서비스의 사용


NOTE: Active IQ 사용자는 ONTAP Collector와 AutoSupport 중에서 선택하여 용량 사용량에 대한 데이터를 가져올 수 있습니다.

.단계
. 상세 * Keystone-용량 활용률 * 대시보드에서 활용률 추세를 보려면 * 세부 정보 보기 * 를 클릭합니다.
. 최근 평균 사용량 추세를 보려면 현재 청구 기간, 30일, 7일 또는 1일을 선택합니다.
+
현재 청구 기간의 경우 버스트 상세 정보를 제공하는 보고서를 다운로드할 수 있습니다.

. 필요에 따라 용량 사용량에 대한 데이터를 얻기 위해 ONTAP Collector를 선택한 경우 대시보드의 탭을 클릭하여 파일 공유 및 디스크에 대한 세부 정보를 볼 수 있습니다.
. 공유 * 또는 * 디스크 * 를 클릭하여 커밋된 용량에 근접하는 파일 공유 또는 디스크를 식별하고 정보를 바탕으로 스토리지 용량 절감을 결정할 수 있습니다.

