---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: renew, hardware, software 
summary: 스토리지 시스템의 소프트웨어 및 하드웨어를 갱신하기 위한 정보를 제공합니다. 
---
= 용량 및 스토리지 효율성 절감 분석
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
시스템의 용량 세부 정보 및 스토리지 효율성 절감 효과를 확인하고 적절한 조치를 취할 수 있습니다. 용량 및 스토리지 효율성 정보는 클러스터 레벨 또는 노드 레벨에서 확인할 수 있습니다.


NOTE: 이 기능은 E-Series 시스템에서 지원되지 않습니다.

용량 대시보드에는 용량 세부 정보와 시스템의 용량 예측이 표시됩니다. 용량 예측은 기간별 용량 정보를 사용하여 각 시스템의 활용도를 식별합니다. 사용 및 할당된 용량의 기록 데이터(사용 가능한 경우 1년 데이터)를 기준으로, 알고리즘은 각 시스템의 현재 사용률을 고려하여 향후 1-6개월 동안 시스템 활용도에 대한 예측을 생성합니다.

스토리지 효율성 대시보드에는 스토리지 효율성 비율, 사용된 논리적 공간, 사용된 물리적 공간 및 ONTAP 9.1 이상을 실행하는 스토리지 시스템에 저장된 총 데이터가 표시됩니다. 효율성 비율과 절감 효과는 AFF 시스템, 비 AFF 시스템 또는 둘 다에 대한 스냅샷 백업을 사용하거나 사용하지 않을 때 나타날 수 있습니다. 고객 스토리지 전반의 총 절감액은 볼륨 중복제거, 볼륨 압축, 컴팩션, FlexClone 볼륨 및 스냅샷 백업과 같은 효율성 기능별로 표시됩니다. 또한 최고의 효율성 비율을 자랑하는 5대 스토리지 시스템을 볼 수도 있습니다.

video::8Ge3_0qlyxA[youtube, width=848,height=480]
.단계
. 왼쪽 창에서 * 용량 및 효율성 * 을 클릭합니다.
+
기본적으로 * Capacity * 탭이 선택됩니다.

. 클러스터 및 노드 레벨에서 용량 세부 정보를 확인합니다.
+
.. 노드 레벨에서 용량 예측을 확인합니다.
+
ONTAP 시스템의 경우, 물리적 용량에 대한 정보는 ClusterViewer에서 확인할 수 있습니다.

.. 용량 추가 * 를 클릭하여 NetApp 또는 파트너에게 알림을 보내 용량을 추가합니다.


. 스토리지 효율성 및 스토리지 시스템의 데이터 절감 효과를 확인하십시오.
+
.. 스토리지 시스템의 스토리지 효율성 비율이 평균 스토리지 효율성 비율보다 높은 경우 * 성공 사례 공유 * 를 클릭하여 모범 사례를 알려주시기 바랍니다.
.. 스토리지 시스템의 스토리지 효율성 비율이 평균 스토리지 효율성 비율보다 낮은 경우 * 연락처 * 를 클릭하여 스토리지 시스템 구성을 알려주십시오.



