---
sidebar: sidebar 
permalink: task_view_performance_graphs.html 
keywords: performance, performance graph, graphs, digital advisor, performance charts, day, week, 1 month, 2 months, calendar, chart data, performance on node level, graph, node level 
summary: 성능에 대한 자세한 내용은 에 나와 있습니다. 
---
= 성능 그래프를 분석합니다
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
성능 그래프를 통해 스토리지 장치의 성능을 분석할 수 있습니다. ONTAP 클러스터 또는 ONTAP 클러스터 및 E-Series 컨트롤러의 다중 노드에 대한 자세한 성능 그래프를 볼 수 있습니다. 이러한 그래프는 성능 추세 및 패턴 분석을 이해하는 데 사용할 수 있는 기간별 성능 데이터를 제공합니다. 달력에서 날짜를 선택하여 일, 주, 월, 2개월 및 12개월의 성능 그래프를 볼 수 있습니다. 여러 노드를 선택하여 특정 그래프를 동시에 볼 수 있습니다.

기본 설정을 지정할 수 있는 옵션이 있습니다. 예를 들어, 3개의 노드에 대해 하나의 그래프 또는 3개의 노드에 대한 2개의 그래프를 볼 수 있습니다.

그래프를 처음 표시하면 1주 탭이 미리 선택되어 그래픽 형식으로 1주 동안의 데이터를 표시하여 대량의 데이터와 여러 데이터 계열 간의 관계를 보다 쉽게 이해할 수 있습니다. 예를 들어 날짜 범위를 다시 설정하려면 1개월 탭을 클릭하고 달력에서 날짜를 선택할 수 있습니다.

또한 성능 그래프를 확대할 수 있는 옵션이 있으며, 개별 데이터 지점이 표시됩니다.

video::fWrHYX17xT8[youtube,width=848,height=480]
.단계
. 대시보드에서 * Performance * 를 클릭합니다.
+
ONTAP 시스템의 경우 * 노드 * 탭을 클릭하여 ONTAP 클러스터의 단일 노드 성능을 확인하거나 * 로컬 계층 * 탭을 클릭하여 로컬 계층의 성능을 확인하거나 * 볼륨 * 탭을 클릭하여 볼륨의 성능을 확인할 수 있습니다. 기본적으로 클러스터 성능이 표시됩니다.

+
E-Series 시스템의 경우 컨트롤러 레벨에서만 그래프를 볼 수 있습니다.



. 1일, 1주, 1개월, 2개월 또는 12개월을 선택합니다. 일정에서 성능 데이터를 그래픽 형식으로 볼 수 있습니다.
+
예를 들어 2개월 탭을 선택하면 2개월 동안의 데이터를 볼 수 있습니다. 이렇게 하면 성과 요구 사항에 따라 기간에 대한 특정 데이터를 볼 수 있습니다.

. ONTAP 클러스터 및 노드에서 다음과 같은 성능 그래프 및 필요한 메트릭을 사용할 수 있습니다.


[cols="25,25,25,25"]
|===
| 클러스터 | 노드 | 로컬 계층의 경우 | 볼륨 


| IOPS | CPU 활용률 - 최대 성능(여유 공간) | 평균 처리량 | IOPS 


| 네트워크 처리량 | 지연 시간 | 평균 사용률 | 지연 시간 


|  | IOPS |  |  


|  | 프로토콜 IOPS |  |  


|  | 네트워크 처리량 |  |  
|===

NOTE: 노드 지연 시간 성능 그래프 및 볼륨 성능 그래프는 ONTAP 9.2 이상을 실행하는 시스템에서만 지원됩니다.

. E-Series 컨트롤러에 필요한 메트릭이 포함된 다음 성능 그래프를 사용할 수 있습니다.
+
** CPU 사용률
** 지연 시간
** IOPS
** 처리량



