---
sidebar: sidebar 
permalink: task_install_execute_firmware_update_exp_user.html 
keywords: install, execute, firmware update, Ansible Playbook, ansible, playbook, docker, experienced user 
summary: Ansible 플레이북을 사용하여 펌웨어 업데이트를 설치 및 실행하는 방법에 대한 정보를 제공합니다. 
---
= AFF 및 FAS 펌웨어 Ansible 자동화 패키지 설치 및 실행(숙련된 사용자)
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
숙련된 사용자는 AFF 및 FAS 펌웨어 Ansible 자동화 패키지를 빠르게 설치 및 실행할 수 있습니다.



== NetApp Docker Image를 사용하여 Ansible으로 펌웨어 업데이트

.단계
. Ansible Docker 이미지를 Linux 호스트로 가져옵니다.
+
[listing]
----
$ docker pull schmots1/netapp-ansible
Using default tag: latest
latest: Pulling from schmots1/netapp-ansible
docker.io/schmots1/netapp-ansible:latest
----
. Linux 호스트에서 Docker 이미지를 컨테이너로 실행합니다.
+
[listing]
----
$ docker run -v <downloaded_playbook_path>:/<container_path> -it schmots1/netapp-ansible:latest /bin/bash
----
+

NOTE: Ansible Playbook과 재고 파일은 같은 경로에 있어야 합니다.

. Linux 호스트에서 Ansible 플레이북을 실행합니다. 펌웨어 업데이트는 백그라운드에서 몇 시간 동안 실행됩니다.
+
[listing]
----
$ cd <container_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware.yml

Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
+

NOTE: 디스크 펌웨어, 쉘프 펌웨어 및 서비스 프로세서 펌웨어의 URL이 *\http://<web-server>/path/all_shelf_fw.zip*, *\http://<web-server>/path/all.zip* 및 *\http://<web-server>/path/<SP/BMC>_<version_number>_fw.zip* 이면 펌웨어 패키지의 기본 URL에 대한 입력으로 *\http://<web-server>/path/* 를 제공합니다. 로그인 자격 증명이 서로 다른 클러스터 세트가 있는 경우 Ansible 플레이북을 각 클러스터에서 실행해야 합니다. Ansible Playbook은 로그인에 실패한 클러스터를 건너뛰어 인벤토리 파일을 변경할 필요가 없습니다.

. 클러스터 관리자로 클러스터에 로그인하고 새 드라이브 펌웨어가 설치되었는지 확인합니다.
+
[listing]
----
::> storage disk show -fields firmware-revision,model
 disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----




== Ansible이 이미 사용 중인 경우 펌웨어 업데이트

.단계
. Python과 Ansible을 설치한 다음 PIP를 사용하여 Python 패키지를 다운로드하십시오.
+
[listing]
----
$ pip install netapp-lib requests paramiko

Installing collected packages: netapp-lib, requests, paramiko
Successfully installed netapp-lib-2020.3.12 requests-2.23.0 paramiko-2.7.2
----
. NetApp Ansible 컬렉션 설치:
+
[listing]
----
To install the collection only for the current user:
$ ansible-galaxy collection install netapp.ontap

For universal installation:
$ ansible-galaxy collection install netapp.ontap -p /usr/share/ansible/collections
$ chmod -R +rw /usr/share/ansible/collections
----
. Ansible Playbook과 인벤토리 파일이 같은 경로에 있는지 확인한 다음 Ansible Playbook을 실행합니다. 펌웨어 업데이트는 백그라운드에서 몇 시간 동안 실행됩니다.
+
[listing]
----
$ cd <playbook_path>
$ ansible-playbook na_ontap_pb_upgrade_firmware_disk.yml

Enter your ONTAP admin username: ****
Enter the password for your ONTAP admin user: ****
Enter the base URL to the firmware package (using HTTP is recommended): http://<web-server>/path/
PLAY [ONTAP Firmware Upgrade] ****************************************************************
----
+

NOTE: 디스크 펌웨어, 쉘프 펌웨어 및 서비스 프로세서 펌웨어의 URL이 *\http://<web-server>/path/all_shelf_fw.zip*, *\http://<web-server>/path/all.zip* 및 *\http://<web-server>/path/<SP/BMC>_<version_number>_fw.zip* 이면 펌웨어 패키지의 기본 URL에 대한 입력으로 *\http://<web-server>/path/* 를 제공합니다. 로그인 자격 증명이 서로 다른 클러스터 세트가 있는 경우 Ansible 플레이북을 각 클러스터에서 실행해야 합니다. Ansible Playbook은 로그인에 실패한 클러스터를 건너뛰어 인벤토리 파일을 변경할 필요가 없습니다.

. 클러스터 관리자로 클러스터에 로그인하고 새 드라이브 펌웨어가 설치되었는지 확인합니다.
+
[listing]
----
::> storage disk show -fields firmware-revision,model
 disk     firmware-revision model
--------------- ----------------- ----------------
1.11.0   NA01              X423_HCOBE900A10
1.11.1   NA01              X423_HCOBE900A10
1.11.2   NA01              X423_HCOBE900A10
1.11.3   NA01              X423_HCOBE900A10
1.11.4   NA01              X423_HCOBE900A10
----

